feed/urls.py
from django.urls import path
from . import views


app_name = 'feed'

urlpatterns = [
    path("",views.HomePage.as_view(), name = "index"),
    path("<int:pk>/",views.PostDetailView.as_view(), name = "detail"),
    path("new/",views.CreatePostView.as_view(),name = "new_post")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feed import urls as feed_urls
from profiles import urls as profiles_url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace="feed")),
    path('profile/', include(profiles_url, namespace="profile")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views


app_name = "profile"

urlpatterns = [
    path("<str:username>/",views.ProfileDetailView.as_view(), name='detail'),
    path("<str:username>/update",views.ProfileUpdateView.as_view(), name='update'),
    path("<str:username>/follow/",views.FollowView.as_view(), name='follow'),
    
    
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
    )
    Image = ImageField(upload_to='profiles')
    

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)   
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class ProfileUpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=140)
    first_name =forms.CharField(max_length=140)
    last_name= forms.CharField(max_length=140)
    email=forms.EmailField(required=False)
 

    class Meta:
        model = Profile
        fields = ["username","Image"]

    def __init__(self,*args, **kwargs):
        user = kwargs.pop('user',None)
        super().__init__(*args,**kwargs)
        if user:
            self.fields['username'].initial = user.username
            self.fields['first_name'].initial = user.first_name
            self.fields['last_name'].initial = user.last_name
            self.fields['email'].initial = user.email

    def save(self, commit=True):
        profile = super().save(commit=False)
        user = profile.user
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            profile.save()
        return profile

        

profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView, View,UpdateView
from feed.models import Post
from django.http import JsonResponse,HttpResponseBadRequest
from django.shortcuts import render
from .models import Profile
from .forms import ProfileUpdateForm
from django.urls import reverse_lazy


from followers.models import Followers
# Create your views here.


class ProfileDetailView(DetailView):
    http_method_names = ['get']
    model= User
    template_name='profiles/detail.html'
    context_object_name="user"
    slug_field="username"
    slug_url_kwarg="username"

    def dispatch(self,request,*args,**kwargs):
        self.request=request

        return super().dispatch(request,*args,**kwargs)
    

    def get_context_data(self,**kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        context['total_followers'] = Followers.objects.filter(followed_by=user).count()

        if self.request.user.is_authenticated:
             context['you_follow']= Followers.objects.filter(following=user,followed_by=self.request.user).exists()
        return context
    

class ProfileUpdateView(UpdateView):
     model = Profile
     form_class = ProfileUpdateForm
     template_name='profiles/update.html'


     def get_success_url(self):
        return reverse_lazy('profile:detail', kwargs={'username': self.object.user.username})


     def get_form_kwargs(self):
          kwargs = super().get_form_kwargs()
          kwargs['user'] = self.request.user
          return kwargs

     def get_object(self, queryset=None):
          content =Profile.objects.get(user__username=self.kwargs['username'])
          return content

class FollowView(View):
        http_method_names = ['post']
        

       
        def post(self, request, *args, **kwargs):
            data = request.POST.dict()
            
            if "action" not in data or "username" not in data:
                return HttpResponseBadRequest("Missing Data")
            
            try:
                 other_user = User.objects.get(username=data['username'])
            except User.DoesNotExist:
                 return HttpResponseBadRequest("Missing Username")
            
            if data['action'] == 'follow':
                 #Follow
                 follower,created = Followers.objects.get_or_create(
                      followed_by=request.user,
                      following=other_user
                 )
            else:
                 #Unfollow
                try:
                    follower = Followers.objects.get(
                        followed_by=request.user,
                        following=other_user
                 )
                except Followers.DoesNotExist:
                     follower=None
                if follower:
                     follower.delete()
                

            return JsonResponse({
                  'success': True,
                  'wording': "Unfollow" if data['action']=="follow" else "Follow"
             })

profiles/templates/profiles/detail.html
{%extends "base.html"%}
{% load thumbnail %}

{%block title%}{{user.username}}{%endblock%}

{%block body%}
<!-- component -->

<div class="rounded-3xl overflow-hidden shadow-xl max-w-xs my-3 bg-blue-500">
    <img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
    <div class="flex justify-center -mt-8 p-3">
        {% thumbnail user.profile.Image "373x373" crop="center" as im %}
        <img src="{{im.url}}" class="rounded-full border-solid border-white border-2 -mt-3">
        {% endthumbnail %}
    </div>
    <div class="text-center px-3 pb-6 pt-2">
        <h3 class="text-white text-sm bold font-sans">{{user.username}}</h3>
        <h3 class="text-white text-sm bold font-sans">{{user.last_name}}</h3>
        <h3 class="text-white text-sm bold font-sans">{{user.first_name}}</h3>
        <h3 class="text-white text-sm bold font-sans">{{user.email}}</h3>
        {%if request.user.is_authenticated %}
        {% if request.user != user %}
        <button
            class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center js-follow"
            data-action="{%if you_follow %}un{%endif%}follow" data-url="{% url 'profile:follow' user.username %}"
            type="button" data-username="{{user.username}}">
            <span class="mr-2 js-follow-text">
                {%if you_follow%}
                UnFollow
                {%else%}
                follow
                {%endif%}
            </span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
            </svg>
        </button>
        {%endif%}
        {%else%}
        <div class="mt-3">Login to Follow</div>
        {%endif%}

    </div>
    <div class="flex justify-center pb-3 text-white">
        <div class="text-center mr-3 border-r pr-3">
            <h2>{{total_posts}} </h2>
            <span>Post</span>
        </div>
        <div class="text-center">
            <h2>{{total_followers}}</h2>
            <span>Followers</span>
        </div>
        {% if request.user.is_authenticated and request.user.username == user.username %}
        
        <div>
            <a  class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-4 inline-flex items-center"href="{% url 'profile:update' user.username %}">
                Update Profile
            </a>
        </div>
        {% endif %}
        
    </div>
</div>
{%endblock%}

profiles/templates/profiles/update.html
{%extends "base.html"%}

{% block body%}
<div class="shadow-wrap">
    <div class="form-wrap">
        <form method='POST' enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
            <input type=submit value="update" data-url="{% url 'profile:detail' user.username %}" />
        </form>
    </div>
</div>

{% endblock%}