feed/urls.py
from django.urls import path
from . import views


app_name = 'feed'

urlpatterns = [
    path("",views.HomePage.as_view(), name = "index"),
    path("<int:pk>/",views.PostDetailView.as_view(), name = "detail"),
    path("new/",views.CreatePostView.as_view(),name = "new_post")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feed import urls as feed_urls
from profiles import urls as profiles_url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace="feed")),
    path('profile/', include(profiles_url, namespace="profile")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/includes/post.html
{% load thumbnail %}
<!-- component -->
<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md">
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{post.date|date:"F j, Y, g:i a"}}</span>
        {% comment %} <a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500" href="#">Design</a> {% endcomment %}
    </div>
    <div class="mt-2" style="width:50rem">
        
        <p class="mt-2 text-gray-600">{{post.text}}</p>
    </div>
    <div class="flex justify-between items-center mt-4">
        {% if show_detail_link %}
        <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">Read more</a>
        {%else%}
        <span>&nbsp;</span>
        {% endif %}
        <div>
            <a class="flex items-center" href="{% url 'profile:detail' post.author.username %}">
                {% thumbnail post.author.profile.Image "373x373" crop="center" as im %}
                     
                     <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{ im.url }}" alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{post.author.username}}</h1>
            </a>
        </div>
    </div>
</div>